version: "3.7"
services:
  rover:
    container_name: rover
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node:rw
